### ISSUE TITLE
Copy and paste in the text editor window for a task?

### ISSUE THREAD

**Issue by jbf7** [ajaxray/geek-life#11]
@ajaxray

**Comment by ajaxray** [comment]
Hi @jbf7,

When you are in internal edit mode (by pressing `e` in detail panel), **Paste** will work without any extra functionality in most of the common terminals. For **Copy**, planning to implement #17 - which will copy the task title and detail to the system clipboard.

Alternatively, if you are editing task detail in external editor (by pressing `v` in detail panel), the default Copy/Paste functionality of editor will work as is.

I am closing this issue as actionable task under this issue is already defined in #17 .
