### ISSUE TITLE
Export Task details 

### ISSUE THREAD

**Issue by rammses** [ajaxray/geek-life#17]
if we could export task details as text or markdown files when it's needed. sharing would've been pretty easy

**Comment by ajaxray** [comment]
Hello @rammses ,
Thanks a lot for sharing your thoughts 👍

As a first step, I am thinking to add a shortcut for "Copy to clipboard" option. That will copy task title, due date and task details to clipboard in a predefined format. So that ot can be written to file or shared via email/messenger. 

I n future, adding integration with Google Tasks (and may be a few more) is in roadmap.
